Repository LEEP-Modelling-Team/AgroManagement, pull requests merged in 2024-04, with the labels that each got.

#9 Iss_06_era5_weather_provider
  agromanagement/core/__init__.py
  agromanagement/core/utils.py
  agromanagement/utility/data_downloaders.py
  environment.yml
  examples/01_sentinel_2_l2a_AWS_downloader.ipynb
  examples/02_sentinel_CDSE_downloader.ipynb
  examples/03_era5_downloader.ipynb
Labels: enhancement, feature

#19 18 readme calibration approach
  readme.md
Labels: documentation

#21 Iss_20_test_CI_workflow
  .github/workflows/ci_workflow.yml
  readme.md
Labels: bug

#23 Added explicit encoding whern saving ERA5 netcds files
  agromanagement/utility/data_downloaders.py
Labels: bug
